s = set()
print(type(s))
s_from_list = set([1, 2, 3, 4])
print(s_from_list)
s.add(2)
s.add(3)
s.add(4)
s.add(3)
s1 = s.union(s, s_from_list)
s2 = s.intersection(s, s_from_list)
s3 = s.isdisjoint(s1)
print(s1)
print(s.isdisjoint(s))
print(s2)
print(s3)
